"""
Filename:
    docs_generate.py

Function:
    Parses human-readable YAML found at ./icons-list.yml and outputs
    a complete HTML website that showcases all icons in the
    "../blender-icons/sets/Lcn-NIS8Eh8o" folder

Important notes:
    Code should be formatted by black and checked for bugs by pylint
"""

import markdown2

# VARIABLES

# File path to the HTML template
template_html = "./template/template.html"

# Autogen warning in the outputted index.html file
auto_warning = """
<!--This file is automatically generated by docs_generate.py.
Please do not modify it, as your changes will be overwritten.
If you would like to edit the styling, refer to template.html instead.-->
"""

# List of markdown files we want to use
markdown_source_list = ["./pages/About.md", "./pages/Contributing.md", "./pages/Usage.md"]

with open(template_html) as html:
    template = html.read()

for markdown_file in markdown_source_list:
    name = markdown_file.split("/").pop()
    filename = name.replace(".md", ".html")
    with open(markdown_file) as mf:
        markdown_textcontent = mf.read()
    html_textcontent = markdown2.markdown(markdown_textcontent)
    markup = template.format(auto_warning, name, html_textcontent)
    # Inject converted HTML into new file
    with open(filename, "w", encoding="utf-8") as output_file:
        output_file.write(markup)
    print(f"Generated {filename} from {markdown_file}")
print("All done!")