"""
Filename:
    yaml2js.py

Function:
    This script creates a JavaScript object from Blendicon's YAML database

Important notes:
    Code should be formatted by black and checked for bugs by pylint
"""

import json
import sys
import yaml

# VARIALBES
data_yaml_file = "icons-list.yml"
WARNING = """/* DO NOT manually edit this file. 
It is auto-generated by yaml2js.py. */
"""

DIST_JS_FILENAME = "./js/iconslist.js"

# First, we need to read the YAML data file which
# contains the necessary database of icon and their
# detailed information
with open(data_yaml_file) as yaml_file:
    # We extract the YAML data as a python dictionary
    # called yaml_data
    yaml_data = yaml.safe_load(yaml_file)
# We now need to convert yaml_data into a list because
# JavaScript only likes to plays nice when looping over arrays
# We transfer the data to a new list called data_array
data_array = []
for item in yaml_data:
    data_array.append(yaml_data[item])
# We now want to serialize the dictionary data
# to a JavaScript object through JSON
json_string = json.dumps(data_array, indent=4)
# Our JavaScript object will be called "iconsList"
javascript_code = WARNING + "let iconsList = {}".format(json_string)
# And we can write the javascript object to an actual file
with open(DIST_JS_FILENAME, "w") as file:
    file.write(javascript_code)
print("Success! Results at", DIST_JS_FILENAME)
